// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'

export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    const request = getRequest();

    if (!request?.headers) {
      throw new Response('Unauthorized: No request headers available', { status: 401 });
    }

    const authHeader = request.headers.get('authorization');

    if (!authHeader) {
      throw new Response('Unauthorized: No authorization header provided', { status: 401 });
    }

    if (!authHeader.startsWith('Bearer ')) {
      throw new Response('Unauthorized: Only Bearer tokens are supported', { status: 401 });
    }

    const token = authHeader.replace('Bearer ', '');
    if (!token) {
      throw new Response('Unauthorized: No token provided', { status: 401 });
    }

    // Firebase ID token verification (required)
    try {
      const { getFirebaseAdminAuth } = await import('@/integrations/firebase/admin.server');
      let firebaseAuth;
      try {
        firebaseAuth = getFirebaseAdminAuth();
      } catch (initError) {
        throw new Response(
          `Server Error: Firebase initialization failed - ${initError instanceof Error ? initError.message : 'unknown error'}`,
          { status: 500 }
        );
      }

      if (!firebaseAuth) {
        throw new Response('Server Error: Firebase not configured', { status: 500 });
      }

      let decoded;
      try {
        decoded = await firebaseAuth.verifyIdToken(token);
      } catch (verifyError) {
        throw new Response('Unauthorized: Invalid or expired token', { status: 401 });
      }

      if (!decoded.uid) {
        throw new Response('Unauthorized: No user ID found in token', { status: 401 });
      }

      return next({
        context: {
          userId: decoded.uid,
          claims: decoded,
        },
      })
    } catch (error) {
      if (error instanceof Response) {
        throw error;
      }
      throw new Response(
        `Server Error: Unexpected auth error - ${error instanceof Error ? error.message : 'unknown error'}`,
        { status: 500 }
      );
    }
  }
)

