// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function resolveClientSupabaseConfig() {
  const urlFromEnv = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const keyFromEnv = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  const isDev = Boolean(import.meta.env.DEV);
  const isBrowser = typeof window !== 'undefined';
  const isLocalHost =
    isBrowser &&
    (window.location.hostname === 'localhost' || window.location.hostname === '127.0.0.1');

  // In local browser development, prefer local Supabase to avoid stale remote env injection.
  const url = isDev && isLocalHost ? (urlFromEnv === 'https://phdhjvvyinbkxytnzwme.supabase.co' ? 'http://127.0.0.1:54321' : urlFromEnv) : urlFromEnv;
  const key =
    isDev && isLocalHost
      ? (keyFromEnv || 'sb_publishable_ACJWlzQHlZjBrEguHvfOxg_3BJgxAaH')
      : keyFromEnv;

  return { url, key };
}

function createSupabaseClient() {
  const { url: SUPABASE_URL, key: SUPABASE_PUBLISHABLE_KEY } = resolveClientSupabaseConfig();

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    throw new Error(
      'Missing Supabase environment variables. Ensure SUPABASE_URL and SUPABASE_PUBLISHABLE_KEY (or VITE_ prefixed versions) are set in your .env file.'
    );
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

